name: syw
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pip
  - pandas
  - notebook
  - scipy
  - pymc>=5
  - arviz
  - pip:
      - matplotlib
      - showyourwork==0.4.3
      - sciris      
      - scikit-learn
      - pydantic
      - pyfcf
      - corner

